name: artemis
version: 3.1.0

authors:
  - Igor Borges <igor@borges.dev>

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  build_config: ^0.4.0
  build: ^1.1.4
  code_builder: ^3.2.0
  equatable: ^1.0.1
  gql_code_gen: ^0.1.5
  gql_dedupe_link: ^1.0.8
  gql_exec: ^0.2.0
  gql_http_link:
    git:
      url: git@github.com:comigor/gql.git
      ref: 570482ebbc025d70e1e977aae68b50c721e8c8e9
      path: gql_http_link
  gql_link: ^0.2.2
  gql: ^0.12.0
  http: ^0.12.0+2
  json_annotation: ^3.0.0
  meta: ^1.1.7
  path: ^1.6.2
  recase: ^2.0.1
  source_gen: ^0.9.4+2

dev_dependencies:
  args: ^1.5.2
  build_runner: ^1.5.0
  build_test: ^0.10.7+3
  json_serializable: ^3.0.0
  pedantic: ^1.8.0+1
  test: ^1.6.3
