name: artemis
version: 2.0.3

authors:
  - Igor Borges <igor@borges.dev>

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build_config: ^0.4.0
  build: ^1.1.4
  code_builder: ^3.2.0
  equatable: ^0.6.1
  glob: ^1.1.7
  gql_code_gen: ^0.1.1
  gql_dedupe_link: ^1.0.4
  gql_http_link: ^0.2.0
  gql: ^0.10.0
  http: ^0.12.0+2
  meta: ^1.1.7
  path: ^1.6.2
  recase: ^2.0.1
  source_gen: ^0.9.4+2

dev_dependencies:
  args: ^1.5.2
  build_runner: ^1.5.0
  build_test: ^0.10.7+3
  json_serializable: ^3.0.0
  pedantic: ^1.8.0+1
  test: ^1.6.3
