name: artemis
version: 6.18.4

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  build_config: ^1.0.0
  build: ^2.0.1
  code_builder: ^3.5.0
  collection: ^1.14.13
  equatable: ^1.2.5
  glob: ^2.0.0
  #gql_code_gen: ^0.1.5
  gql_build: ^0.2.0
  gql_code_builder: ^0.2.0
  gql_dedupe_link: ^2.0.0
  gql_exec: ^0.3.0
  gql_http_link: ^0.4.0
  gql_link: ^0.4.0
  gql: ^0.13.0
  http: ^0.13.3
  json_annotation: ^4.0.1
  meta: ^1.2.4
  path: ^1.7.0
  recase: ^4.0.0
  source_gen: ^1.0.0
  yaml: ^3.0.0
dependency_overrides:
  dart_style: 2.0.1

dev_dependencies:
  args: ^2.1.0
  build_runner: ^1.10.11
  build_test: ^1.3.2
  json_serializable: ^4.1.2
  build_resolvers: ^1.5.1
  pedantic: ^1.9.2
  test: ^1.15.7
  logging: ^0.11.4
