name: artemis
version: 6.18.4

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  build_config: ^1.0.0
  build: ^2.1.0
  code_builder: ^4.1.0
  collection: ^1.14.13
  dart_style: ^2.2.3
  equatable: ^1.2.5
  glob: ^2.0.2
  gql_dedupe_link: ^2.0.2
  gql_exec: ^0.4.0
  gql_http_link: ^0.4.2
  gql_link: ^0.4.2
  gql: ^0.13.1
  http: ^0.13.4
  json_annotation: ^4.4.0
  meta: ^1.2.4
  path: ^1.7.0
  recase: ^3.0.1
  source_gen: ^1.2.2
  yaml: ^3.1.0

dev_dependencies:
  args: ^2.3.0
  build_runner: ^2.1.5
  build_test: ^2.1.5
  json_serializable: ^6.1.1
  build_resolvers: ^2.0.8
  logging: ^1.0.0
  pedantic: ^1.9.2
  test: ^1.15.7
