name: artemis
version: 7.0.0-nullsafety

description: Build dart types from GraphQL schemas and queries (using Introspection Query).
homepage: https://github.com/comigor/artemis

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  build_config: ^0.4.5
  build: ^1.6.1
  gql_code_gen: ^0.1.5
  gql_dedupe_link: ^1.0.10
  gql_exec: ^0.2.5
  gql_http_link: ^0.3.2
  gql_link: ^0.3.1-alpha
  gql: ^0.12.4
  code_builder: ^3.6.0
  collection: ^1.15.0-nullsafety.4
  dart_style: ^1.3.11
  equatable: ^2.0.0-nullsafety.1
  glob: ^2.0.0-nullsafety.0
  http: ^0.12.2
  json_annotation: ^4.0.0-nullsafety.0
  meta: ^1.2.4
  path: ^1.7.0
  recase: ^4.0.0-nullsafety.0
  source_gen: ^0.9.10+1
  yaml: ^3.0.0-nullsafety.0

dev_dependencies:
  args: ^2.0.0-nullsafety.0
  build_runner: ^1.11.0
  build_test: ^1.3.4
  json_serializable: ^4.0.0-nullsafety.0
  build_resolvers: ^1.5.2
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.16
  logging: ^1.0.0-nullsafety.0

dependency_overrides:
  http_parser: ^4.0.0-nullsafety
  glob: ^2.0.0-nullsafety.0
  args: ^2.0.0-nullsafety.0
  logging: ^1.0.0-nullsafety.0
  gql:
    path: /Users/Shared/workspace/pub.dev/gql/gql/