targets:
  $default:
    sources:
      - lib/**
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/pokemon.schema.json
              queries_glob: lib/**.query.graphql
