targets:
  $default:
    sources:
      - lib/**
      - pokemon.schema.json
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: pokemon.schema.json
              queries_glob: lib/**.query.graphql
