name: Package analyzer
on: [push, pull_request]

jobs:

  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: axel-op/dart-package-analyzer@stable
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
